"""Top-of-dashboard 4-axis small-multiples summary.

For each Track 2 axis, draws a compact trajectory chart with all four
astronauts overlaid. Used as the entry point on the Risk Profiles tab so
judges see the full per-astronaut, per-axis picture at a glance before
drilling into individual axes.
"""

from __future__ import annotations

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import streamlit as st

from guiv2 import config, data


def render_risk_overview(view: dict, manifest: dict) -> None:
    st.subheader(view["title"])

    dashboard = data.load_json(view["json"])
    if not dashboard:
        st.error(f"Could not load risk-profile JSON at `{view['json']}`. "
                 "Run risk_profile_claude/build_risk_profile.py first.")
        return

    axes = dashboard.get("axes", [])
    if not axes:
        st.warning("No axes in the risk-profile JSON.")
        return

    timepoints = dashboard["metadata"]["timepoints"]
    crew_names = data.crew_display_names(manifest)

    rows, cols = config.RISK_OVERVIEW_GRID
    if rows * cols < len(axes):
        rows = (len(axes) + cols - 1) // cols  # grow rows to fit
    titles = []
    for ax in axes[: rows * cols]:
        flag = ""
        if ax.get("is_mock"):         flag = "  [mock]"
        elif ax.get("is_cohort_level"): flag = "  [cohort-level]"
        titles.append(ax.get("label", ax.get("id", "?")) + flag)

    fig = make_subplots(
        rows=rows, cols=cols,
        subplot_titles=titles,
        shared_xaxes=False,
        horizontal_spacing=0.08,
        vertical_spacing=0.18,
    )

    # we want one shared legend across subplots — show the legend only on
    # the first subplot, suppress on the rest.
    legend_shown_for: set[str] = set()

    for i, axis in enumerate(axes[: rows * cols]):
        r = i // cols + 1
        c = i % cols + 1
        for crew_id, traj in axis.get("trajectories", {}).items():
            ys = traj.get("scores", [None] * len(timepoints))
            color = config.CREW_COLORS.get(crew_id, "#444")
            show_legend = crew_id not in legend_shown_for
            legend_shown_for.add(crew_id)
            fig.add_trace(
                go.Scatter(
                    x=timepoints, y=ys,
                    mode="lines+markers",
                    name=crew_names.get(crew_id, crew_id),
                    line=dict(color=color, width=2),
                    marker=dict(size=5, color=color),
                    legendgroup=crew_id,
                    showlegend=show_legend,
                    connectgaps=False,
                    hovertemplate=(f"<b>{crew_names.get(crew_id, crew_id)}"
                                   f" — {axis.get('label')}</b>"
                                   "<br>%{x}: %{y:.2f}<extra></extra>"),
                ),
                row=r, col=c,
            )
        fig.add_hline(y=0, line_color="#bbb", line_width=1, row=r, col=c)

    fig.update_layout(
        height=420 * rows,
        margin=dict(l=10, r=10, t=60, b=40),
        legend=dict(orientation="h", yanchor="bottom", y=1.04,
                    xanchor="center", x=0.5),
        hovermode="closest",
    )
    fig.update_xaxes(tickfont=dict(size=9))
    fig.update_yaxes(tickfont=dict(size=10), zeroline=False)
    st.plotly_chart(fig, use_container_width=True)

    # quick-glance table: who deviated most at R+1 on each axis
    st.markdown("### R+1 deviation rank per axis")
    rows_data = []
    target_tp = view.get("ranking_at", "R+1")
    if target_tp not in timepoints:
        target_tp = timepoints[0]
    target_idx = timepoints.index(target_tp)
    for axis in axes:
        ranking = []
        for crew_id, traj in axis.get("trajectories", {}).items():
            scores = traj.get("scores", [])
            v = scores[target_idx] if target_idx < len(scores) else None
            if v is not None:
                ranking.append((crew_id, v))
        ranking.sort(key=lambda r: abs(r[1]), reverse=True)
        rows_data.append({
            "Axis": axis.get("label", axis.get("id")),
            f"Highest |deviation| at {target_tp}":
                (f"{crew_names.get(ranking[0][0], ranking[0][0])} "
                 f"({ranking[0][1]:+.2f})") if ranking else "—",
            "2nd": (f"{crew_names.get(ranking[1][0], ranking[1][0])} "
                    f"({ranking[1][1]:+.2f})") if len(ranking) > 1 else "—",
            "3rd": (f"{crew_names.get(ranking[2][0], ranking[2][0])} "
                    f"({ranking[2][1]:+.2f})") if len(ranking) > 2 else "—",
            "4th": (f"{crew_names.get(ranking[3][0], ranking[3][0])} "
                    f"({ranking[3][1]:+.2f})") if len(ranking) > 3 else "—",
        })
    st.dataframe(rows_data, hide_index=True, use_container_width=True)

    st.caption(
        f"Generated by `{dashboard['metadata'].get('generator', '?')}` at "
        f"`{dashboard['metadata'].get('generated_at', '?')}`."
    )
